name: Deploy Application to Server

on:
  push:
    branches: ["main"]

jobs:
  laravel-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd domains/scrapeniche.com/public_html
            git fetch --all
            git reset --hard origin/main
            git pull

            if [ -n "$(git diff HEAD@{1})" ]; then
              php artisan optimize:clear
              if [ -n "$(git diff HEAD@{1} --name-only | grep 'composer.json')" ]; then
                composer2 install --no-dev --optimize-autoloader --no-interaction
              fi
            fi
